version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5433:5432"
    image: postgres:16.3-alpine

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db_auth_vol:/var/lib/postgresql/data

volumes:
  db_auth_vol: {}