version: '3.5'
# 6100 -auth
#6101 -db_auth
#6200 -data
#6201 -db_data
services:
  db_auth:
    container_name: db_auth
    ports:
      - "6101:6101"
    image: postgres:16.3-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6101"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db_auth_vol:/var/lib/postgresql/data

volumes:
  db_auth_vol: {}